apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutum-deployment
spec:
  selector:
    matchLabels:
      app: tutum
  template:
    metadata:
      labels:
        app: tutum
    spec:
      containers:
      - name: tutum
        image: tutum/hello-world
        ports:
        - containerPort: 80
