---
kind: Namespace
apiVersion: v1
metadata:
  name: development
  labels:
    name: development

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-svc-acct
  namespace: development
  labels:
    name: nginx-svc-acct